version: '3'

services:
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'game-php'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 64M

  apachephp:
    build:
      apachephp
    depends_on:
      - mysql
    ports:
      - 8001:80
    volumes:
      - ./apachephp/vhosts:/etc/apache2/sites-enabled
      - ./app:/var/www
